### ISSUE TITLE
Dependencies installed if collector_is_containerized is defined

### ISSUE THREAD

**Issue by rogercoll** [newrelic-experimental/caos-ansible-roles#9]
The meta information of the `opentelemetry_collector` role should only install the dependencies if `collector_is_containerized` equals to false. Currently, if the user defines it, whether to true or false it will try to run the dependencies:

```
dependencies:
  - role: 'geerlingguy.pip'
    when: collector_is_containerized
    vars:
      pip_install_packages:
        - docker
  - { role: 'geerlingguy.docker', when: collector_is_containerized }
```
